const countries = [
    { id: 2, country: "Azerbaijan" },
    { id: 3, country: "Albania" },
    { id: 4, country: "Armenia" },
    { id: 5, country: "Bosnia and Herzegovina" },
    { id: 6, country: "Bulgaria" },
    { id: 7, country: "Cyprus" },
    { id: 8, country: "Denmark" },
    { id: 9, country: "Ireland" },
    { id: 10, country: "Estonia" },
    { id: 11, country: "Austria" },
    { id: 12, country: "Czech Republic" },
    { id: 13, country: "Finland" },
    { id: 14, country: "France" },
    { id: 15, country: "Georgia" },
    { id: 16, country: "Germany" },
    { id: 17, country: "Greece" },
    { id: 18, country: "Croatia" },
    { id: 19, country: "Hungary" },
    { id: 20, country: "Iceland" },
    //{ id: 21, country: "Israel" },
    { id: 22, country: "Italy" },
    { id: 23, country: "Latvia" },
    { id: 24, country: "Belarus" },
    { id: 25, country: "Lithuania" },
    { id: 26, country: "Slovakia" },
    { id: 27, country: "Liechtenstein" },
    { id: 28, country: "Macedonia" },
    { id: 29, country: "Malta" },
    { id: 30, country: "Belgium" },
    //{ id: 31, country: "Faroe Islands" },
    { id: 32, country: "Andorra" },
    { id: 33, country: "Luxembourg" },
    { id: 34, country: "Monaco" },
    { id: 35, country: "Montenegro" },
    { id: 36, country: "Netherlands" },
    { id: 37, country: "Norway" },
    { id: 38, country: "Poland" },
    { id: 39, country: "Portugal" },
    { id: 40, country: "Romania" },
    { id: 41, country: "Republic of Moldova" },
    { id: 42, country: "Slovenia" },
    { id: 43, country: "Spain" },
    { id: 44, country: "Sweden" },
    { id: 45, country: "Switzerland" },
    { id: 46, country: "Turkey" },
    { id: 47, country: "United Kingdom" },
    { id: 48, country: "Ukraine" },
    { id: 49, country: "San Marino" },
    { id: 50, country: "Serbia" },
    { id: 51, country: "Holy See (Vatican City)" },
    { id: 52, country: "Russia" },
  ];

  export default countries